version: "3"

volumes:
  data:
  testdata:

services:
  postgres_container:
    image: postgres:12
    restart: always
    ports:
      - '54320:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
